# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Samuel B. MONGOUE"
resume_title:                   "Inspecteur de la sécurité nucléaire"
resume_contact_email:           "baudrysamuel.mongoueyamkam@edu.ece.fr"
resume_contact_telephone:       "+33 07 59 51 51 13"
resume_contact_address:         "9 Avenue Massenet, Ozoir la Ferrière"
resume_header_contact_info: "9 Avenue Massenet, Ozoir la Ferrière | +33 07 59 51 51 13 | baudrysamuel.mongoueyamkam@edu.ece.fr"
resume_header_intro: "<p>Ceci est le résumé exécutif. Vous devez écrire quelques phrases brèves, concises et significatives sur vous-même dans un contexte professionnel, ainsi que vos objectifs de carrière immédiats. Adaptez la longueur à vos besoins, mais restez simple et direct.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
